### ISSUE TITLE
Hacktoberfest: Toxic comment classification demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-classification-toxic-comment#1]
This is the tracker for polishing the “Toxic comment classification” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Update README to include:
    - [x] Short description
        - [x] short explanation on how classification with Weaviate works
    - [x] used technology
        - [x] used Weaviate modules/ML models
    - [x]  demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [x] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point) (claimed by @aaalexlit)
    - [x] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by aaalexlit** [comment]
Hi @iamleonie!
I'd like to take this one and start with conversion to the new Python client (that will automatically include the readme part)
Also, I'd like to replace the UI potentially with Gradio.
These in my view represent pretty dramatic changes to the code.
Once this is done I'm eager to proceed with zero-shot, similar comments, tests, and other potential improvements

**Comment by iamleonie** [comment]
Thanks for volunteering @aaalexlit . That sounds great!

**Comment by CS-Edwards** [comment]
Hey @iamleonie !

I'd like to update the README : short description and tech stack , and add some tests (PyTest)

cheers,
c

**Comment by iamleonie** [comment]
Hey @CS-Edwards, thank you for volunterring. From what I understand, @aaalexlit is already working on those points. 

It would be great if you both could align here (or feel free to use the #hacktoberfest channel in [our community Slack](https://weaviate.slack.com/join/shared_invite/zt-23qrfy0vb-5U8cguiniDlhd84WBWiRgg#/shared-invite/email)) if @CS-Edwards could maybe also take over a few items (maybe getting started with adding tests?) 
Thank you so much for your collaboration!

**Comment by CS-Edwards** [comment]
No worries! I'll leave those to @aaalexlit . Thanks @iamleonie !

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
